title: Alhassan Fadillilah
logo: assets/img/profile.png
description: Data Scientist & Health Analytics Specialist
theme: jekyll-theme-minimal

# Social links (displayed in the sidebar)
plugins:
  - jekyll-seo-tag
