title: Alhassan Fadillilah
logo: assets/photo_2026-05-19_14-12-03.jpg
description: Data Scientist & Health Analytics Specialist
theme: jekyll-theme-minimal

# Social links (displayed in the sidebar)
plugins:
  - jekyll-seo-tag
